var hierarchy =
[
    [ "bsppp::BSP", "d5/dba/classbsppp_1_1BSP.html", [
      [ "vpkpp::BSP", "d2/da8/classvpkpp_1_1BSP.html", null ]
    ] ],
    [ "dmxpp::DMX", "d1/d5f/classdmxpp_1_1DMX.html", null ],
    [ "dmxpp::DMXAttribute", "dc/d56/structdmxpp_1_1DMXAttribute.html", null ],
    [ "dmxpp::DMXElement", "d4/d6d/structdmxpp_1_1DMXElement.html", null ],
    [ "dmxpp::Value::Color", "da/db5/structdmxpp_1_1Value_1_1Color.html", null ],
    [ "dmxpp::Value::Element", "dc/d06/structdmxpp_1_1Value_1_1Element.html", null ],
    [ "dmxpp::Value::Invalid", "da/dee/structdmxpp_1_1Value_1_1Invalid.html", null ],
    [ "dmxpp::Value::Time", "d5/d19/structdmxpp_1_1Value_1_1Time.html", null ],
    [ "fgdpp::FGD", "d7/d45/classfgdpp_1_1FGD.html", null ],
    [ "fgdpp::FGD::AutoVisGroup", "d5/d38/structfgdpp_1_1FGD_1_1AutoVisGroup.html", null ],
    [ "fgdpp::FGD::Entity", "d8/d96/structfgdpp_1_1FGD_1_1Entity.html", null ],
    [ "fgdpp::FGD::Entity::ClassProperty", "d0/dfe/structfgdpp_1_1FGD_1_1Entity_1_1ClassProperty.html", null ],
    [ "fgdpp::FGD::Entity::Field", "db/d07/structfgdpp_1_1FGD_1_1Entity_1_1Field.html", null ],
    [ "fgdpp::FGD::Entity::FieldChoices", "d4/d95/structfgdpp_1_1FGD_1_1Entity_1_1FieldChoices.html", null ],
    [ "fgdpp::FGD::Entity::FieldChoices::Choice", "d4/df1/structfgdpp_1_1FGD_1_1Entity_1_1FieldChoices_1_1Choice.html", null ],
    [ "fgdpp::FGD::Entity::FieldFlags", "d3/d1c/structfgdpp_1_1FGD_1_1Entity_1_1FieldFlags.html", null ],
    [ "fgdpp::FGD::Entity::FieldFlags::Flag", "d0/d27/structfgdpp_1_1FGD_1_1Entity_1_1FieldFlags_1_1Flag.html", null ],
    [ "fgdpp::FGD::Entity::IO", "db/de2/structfgdpp_1_1FGD_1_1Entity_1_1IO.html", null ],
    [ "fgdpp::FGDWriter", "d5/db1/classfgdpp_1_1FGDWriter.html", null ],
    [ "fgdpp::FGDWriter::AutoVisGroupWriter", "d1/d08/classfgdpp_1_1FGDWriter_1_1AutoVisGroupWriter.html", null ],
    [ "fgdpp::FGDWriter::EntityWriter", "d9/ddd/classfgdpp_1_1FGDWriter_1_1EntityWriter.html", null ],
    [ "fgdpp::FGDWriter::EntityWriter::KeyValueChoicesWriter", "d7/daf/classfgdpp_1_1FGDWriter_1_1EntityWriter_1_1KeyValueChoicesWriter.html", null ],
    [ "fgdpp::FGDWriter::EntityWriter::KeyValueFlagsWriter", "d0/d3b/classfgdpp_1_1FGDWriter_1_1EntityWriter_1_1KeyValueFlagsWriter.html", null ],
    [ "gamepp::GameInstance", "d2/dc0/classgamepp_1_1GameInstance.html", null ],
    [ "kvpp::KV1Element", "da/daf/classkvpp_1_1KV1Element.html", [
      [ "kvpp::KV1", "de/d0f/classkvpp_1_1KV1.html", null ]
    ] ],
    [ "sourcepp::math::Matrix< 3, 4 >", "d4/d4b/classsourcepp_1_1math_1_1Matrix.html", null ],
    [ "mdlpp::BakedModel", "de/d21/structmdlpp_1_1BakedModel.html", null ],
    [ "mdlpp::BakedModel::Mesh", "d2/d2f/structmdlpp_1_1BakedModel_1_1Mesh.html", null ],
    [ "mdlpp::BakedModel::Vertex", "d3/d83/structmdlpp_1_1BakedModel_1_1Vertex.html", null ],
    [ "mdlpp::BBox", "d9/dd3/structmdlpp_1_1BBox.html", null ],
    [ "mdlpp::MDL::BodyPart", "d1/d46/structmdlpp_1_1MDL_1_1BodyPart.html", null ],
    [ "mdlpp::MDL::Bone", "d2/dbf/structmdlpp_1_1MDL_1_1Bone.html", null ],
    [ "mdlpp::MDL::BoneController", "d3/d2f/structmdlpp_1_1MDL_1_1BoneController.html", null ],
    [ "mdlpp::MDL::HitboxSet", "d0/db5/structmdlpp_1_1MDL_1_1HitboxSet.html", null ],
    [ "mdlpp::MDL::Material", "db/dbe/structmdlpp_1_1MDL_1_1Material.html", null ],
    [ "mdlpp::MDL::MDL", "d5/daa/structmdlpp_1_1MDL_1_1MDL.html", null ],
    [ "mdlpp::MDL::Mesh", "df/de5/structmdlpp_1_1MDL_1_1Mesh.html", null ],
    [ "mdlpp::MDL::Model", "d5/da2/structmdlpp_1_1MDL_1_1Model.html", null ],
    [ "mdlpp::Movement", "d1/dbd/structmdlpp_1_1Movement.html", null ],
    [ "mdlpp::StudioModel", "db/dee/structmdlpp_1_1StudioModel.html", null ],
    [ "mdlpp::VTX::BodyPart", "d1/db8/structmdlpp_1_1VTX_1_1BodyPart.html", null ],
    [ "mdlpp::VTX::Mesh", "de/d89/structmdlpp_1_1VTX_1_1Mesh.html", null ],
    [ "mdlpp::VTX::Model", "d2/d68/structmdlpp_1_1VTX_1_1Model.html", null ],
    [ "mdlpp::VTX::ModelLOD", "d2/dd4/structmdlpp_1_1VTX_1_1ModelLOD.html", null ],
    [ "mdlpp::VTX::Strip", "d3/db9/structmdlpp_1_1VTX_1_1Strip.html", null ],
    [ "mdlpp::VTX::StripGroup", "da/d15/structmdlpp_1_1VTX_1_1StripGroup.html", null ],
    [ "mdlpp::VTX::Vertex", "d0/d6e/structmdlpp_1_1VTX_1_1Vertex.html", null ],
    [ "mdlpp::VTX::VTX", "d5/dd3/structmdlpp_1_1VTX_1_1VTX.html", null ],
    [ "mdlpp::VVD::BoneWeight", "d8/de6/structmdlpp_1_1VVD_1_1BoneWeight.html", null ],
    [ "mdlpp::VVD::Fixup", "d0/d4d/structmdlpp_1_1VVD_1_1Fixup.html", null ],
    [ "mdlpp::VVD::Vertex", "dc/d30/structmdlpp_1_1VVD_1_1Vertex.html", null ],
    [ "mdlpp::VVD::VVD", "d0/de2/structmdlpp_1_1VVD_1_1VVD.html", null ],
    [ "sourcepp::math::FloatCompressed16", "d4/db7/classsourcepp_1_1math_1_1FloatCompressed16.html", null ],
    [ "sourcepp::math::Matrix< M, N, P >", "d4/d4b/classsourcepp_1_1math_1_1Matrix.html", null ],
    [ "sourcepp::math::QuatCompressed48", "d7/d84/structsourcepp_1_1math_1_1QuatCompressed48.html", null ],
    [ "sourcepp::math::QuatCompressed64", "d4/daf/structsourcepp_1_1math_1_1QuatCompressed64.html", null ],
    [ "sourcepp::math::Vec< S, P >", "d6/d21/structsourcepp_1_1math_1_1Vec.html", null ],
    [ "std::exception", null, [
      [ "std::runtime_error", null, [
        [ "sourcepp::parser::text::syntax_error", "d7/d77/classsourcepp_1_1parser_1_1text_1_1syntax__error.html", null ]
      ] ]
    ] ],
    [ "steampp::Steam", "d9/d81/classsteampp_1_1Steam.html", null ],
    [ "vpkpp::Entry", "d9/d6b/classvpkpp_1_1Entry.html", null ],
    [ "vpkpp::EntryOptions", "d6/d5b/structvpkpp_1_1EntryOptions.html", null ],
    [ "vpkpp::GCF::Block", "d4/d3e/structvpkpp_1_1GCF_1_1Block.html", null ],
    [ "vpkpp::GCF::BlockHeader", "d9/d14/structvpkpp_1_1GCF_1_1BlockHeader.html", null ],
    [ "vpkpp::GCF::ChecksumMapEntry", "d3/def/structvpkpp_1_1GCF_1_1ChecksumMapEntry.html", null ],
    [ "vpkpp::GCF::ChecksumMapHeader", "dc/db5/structvpkpp_1_1GCF_1_1ChecksumMapHeader.html", null ],
    [ "vpkpp::GCF::DataBlockHeader", "db/ddb/structvpkpp_1_1GCF_1_1DataBlockHeader.html", null ],
    [ "vpkpp::GCF::DirectoryEntry", "d1/d62/structvpkpp_1_1GCF_1_1DirectoryEntry.html", null ],
    [ "vpkpp::GCF::DirectoryEntry2", "dd/de9/structvpkpp_1_1GCF_1_1DirectoryEntry2.html", null ],
    [ "vpkpp::GCF::DirectoryHeader", "d0/d21/structvpkpp_1_1GCF_1_1DirectoryHeader.html", null ],
    [ "vpkpp::GCF::DirectoryMapEntry", "d9/dd6/structvpkpp_1_1GCF_1_1DirectoryMapEntry.html", null ],
    [ "vpkpp::GCF::DirectoryMapHeader", "d4/dcd/structvpkpp_1_1GCF_1_1DirectoryMapHeader.html", null ],
    [ "vpkpp::GCF::Header", "d3/d08/structvpkpp_1_1GCF_1_1Header.html", null ],
    [ "vpkpp::GMA::Header", "dc/d1f/structvpkpp_1_1GMA_1_1Header.html", null ],
    [ "vpkpp::PackFile", "d2/dd2/classvpkpp_1_1PackFile.html", [
      [ "vpkpp::EXAMPLE", "d2/d8b/classvpkpp_1_1EXAMPLE.html", null ],
      [ "vpkpp::GMA", "d6/d2c/classvpkpp_1_1GMA.html", null ],
      [ "vpkpp::PAK", "d9/daf/classvpkpp_1_1PAK.html", null ],
      [ "vpkpp::PCK", "d5/db5/classvpkpp_1_1PCK.html", null ],
      [ "vpkpp::PackFileReadOnly", "de/df6/classvpkpp_1_1PackFileReadOnly.html", [
        [ "vpkpp::GCF", "d1/d01/classvpkpp_1_1GCF.html", null ]
      ] ],
      [ "vpkpp::VPK", "d5/d8b/classvpkpp_1_1VPK.html", [
        [ "vpkpp::FPX", "da/d42/classvpkpp_1_1FPX.html", null ]
      ] ],
      [ "vpkpp::VPK_VTMB", "d4/ddb/classvpkpp_1_1VPK__VTMB.html", null ],
      [ "vpkpp::ZIP", "da/de7/classvpkpp_1_1ZIP.html", [
        [ "vpkpp::BSP", "d2/da8/classvpkpp_1_1BSP.html", null ]
      ] ]
    ] ],
    [ "vpkpp::PackFileOptions", "d5/db7/structvpkpp_1_1PackFileOptions.html", null ],
    [ "vpkpp::PCK::Header", "d5/da3/structvpkpp_1_1PCK_1_1Header.html", null ],
    [ "vpkpp::VPK::Footer2", "d5/dde/structvpkpp_1_1VPK_1_1Footer2.html", null ],
    [ "vpkpp::VPK::FreedChunk", "d9/de4/structvpkpp_1_1VPK_1_1FreedChunk.html", null ],
    [ "vpkpp::VPK::Header1", "d2/d67/structvpkpp_1_1VPK_1_1Header1.html", null ],
    [ "vpkpp::VPK::Header2", "d2/d8d/structvpkpp_1_1VPK_1_1Header2.html", null ],
    [ "vpkpp::VPK::MD5Entry", "dd/dc7/structvpkpp_1_1VPK_1_1MD5Entry.html", null ],
    [ "vtfpp::Resource", "d3/d80/structvtfpp_1_1Resource.html", null ],
    [ "vtfpp::VTF", "d8/df2/classvtfpp_1_1VTF.html", null ]
];