var hierarchy =
[
    [ "bsppp::BSP", "d5/dba/classbsppp_1_1BSP.html", null ],
    [ "bsppp::BSPBrushModel_v0", "d3/db0/structbsppp_1_1BSPBrushModel__v0.html", null ],
    [ "bsppp::BSPEdge_v0", "d8/d16/structbsppp_1_1BSPEdge__v0.html", null ],
    [ "bsppp::BSPEdge_v1", "dd/d95/structbsppp_1_1BSPEdge__v1.html", null ],
    [ "bsppp::BSPFace_v1", "d6/d98/structbsppp_1_1BSPFace__v1.html", null ],
    [ "bsppp::BSPFace_v2", "d8/d85/structbsppp_1_1BSPFace__v2.html", null ],
    [ "bsppp::BSPPlane_v0", "d8/de4/structbsppp_1_1BSPPlane__v0.html", null ],
    [ "bsppp::BSPSurfEdge_v0", "df/d2e/structbsppp_1_1BSPSurfEdge__v0.html", null ],
    [ "bsppp::BSPTextureData_v0", "d1/d93/structbsppp_1_1BSPTextureData__v0.html", null ],
    [ "bsppp::BSPTextureInfo_v0", "d3/d0f/structbsppp_1_1BSPTextureInfo__v0.html", null ],
    [ "bsppp::BSPVertex_v0", "d2/d27/structbsppp_1_1BSPVertex__v0.html", null ],
    [ "dmxpp::DMX", "d1/d5f/classdmxpp_1_1DMX.html", null ],
    [ "dmxpp::DMXAttribute", "dc/d56/structdmxpp_1_1DMXAttribute.html", null ],
    [ "dmxpp::DMXElement", "d4/d6d/structdmxpp_1_1DMXElement.html", null ],
    [ "dmxpp::Value::Color", "da/db5/structdmxpp_1_1Value_1_1Color.html", null ],
    [ "dmxpp::Value::Element", "dc/d06/structdmxpp_1_1Value_1_1Element.html", null ],
    [ "dmxpp::Value::Invalid", "da/dee/structdmxpp_1_1Value_1_1Invalid.html", null ],
    [ "dmxpp::Value::Time", "d5/d19/structdmxpp_1_1Value_1_1Time.html", null ],
    [ "gamepp::GameInstance", "d2/dc0/classgamepp_1_1GameInstance.html", null ],
    [ "kvpp::KV1ElementBase< std::string, KV1ElementWritable< std::string > >", "de/d62/classkvpp_1_1KV1ElementBase.html", [
      [ "kvpp::KV1ElementWritable< std::string >", "de/d75/classkvpp_1_1KV1ElementWritable.html", [
        [ "kvpp::KV1Writer< S >", "d4/d43/classkvpp_1_1KV1Writer.html", null ]
      ] ],
      [ "kvpp::KV1ElementWritable< S >", "de/d75/classkvpp_1_1KV1ElementWritable.html", null ]
    ] ],
    [ "kvpp::KV1ElementBase< std::string_view, KV1ElementReadable >", "de/d62/classkvpp_1_1KV1ElementBase.html", [
      [ "kvpp::KV1ElementReadable", "d4/d2d/classkvpp_1_1KV1ElementReadable.html", [
        [ "kvpp::KV1", "de/d0f/classkvpp_1_1KV1.html", null ]
      ] ]
    ] ],
    [ "kvpp::KV1ElementBase< S, K >", "de/d62/classkvpp_1_1KV1ElementBase.html", null ],
    [ "sourcepp::math::Matrix< 3, 4 >", "d4/d4b/classsourcepp_1_1math_1_1Matrix.html", null ],
    [ "mdlpp::BakedModel", "de/d21/structmdlpp_1_1BakedModel.html", null ],
    [ "mdlpp::BakedModel::Mesh", "d2/d2f/structmdlpp_1_1BakedModel_1_1Mesh.html", null ],
    [ "mdlpp::BakedModel::Vertex", "d3/d83/structmdlpp_1_1BakedModel_1_1Vertex.html", null ],
    [ "mdlpp::BBox", "d9/dd3/structmdlpp_1_1BBox.html", null ],
    [ "mdlpp::MDL::BodyPart", "d1/d46/structmdlpp_1_1MDL_1_1BodyPart.html", null ],
    [ "mdlpp::MDL::Bone", "d2/dbf/structmdlpp_1_1MDL_1_1Bone.html", null ],
    [ "mdlpp::MDL::BoneController", "d3/d2f/structmdlpp_1_1MDL_1_1BoneController.html", null ],
    [ "mdlpp::MDL::HitboxSet", "d0/db5/structmdlpp_1_1MDL_1_1HitboxSet.html", null ],
    [ "mdlpp::MDL::Material", "db/dbe/structmdlpp_1_1MDL_1_1Material.html", null ],
    [ "mdlpp::MDL::MDL", "d5/daa/structmdlpp_1_1MDL_1_1MDL.html", null ],
    [ "mdlpp::MDL::Mesh", "df/de5/structmdlpp_1_1MDL_1_1Mesh.html", null ],
    [ "mdlpp::MDL::Model", "d5/da2/structmdlpp_1_1MDL_1_1Model.html", null ],
    [ "mdlpp::Movement", "d1/dbd/structmdlpp_1_1Movement.html", null ],
    [ "mdlpp::StudioModel", "db/dee/structmdlpp_1_1StudioModel.html", null ],
    [ "mdlpp::VTX::BodyPart", "d1/db8/structmdlpp_1_1VTX_1_1BodyPart.html", null ],
    [ "mdlpp::VTX::Mesh", "de/d89/structmdlpp_1_1VTX_1_1Mesh.html", null ],
    [ "mdlpp::VTX::Model", "d2/d68/structmdlpp_1_1VTX_1_1Model.html", null ],
    [ "mdlpp::VTX::ModelLOD", "d2/dd4/structmdlpp_1_1VTX_1_1ModelLOD.html", null ],
    [ "mdlpp::VTX::Strip", "d3/db9/structmdlpp_1_1VTX_1_1Strip.html", null ],
    [ "mdlpp::VTX::StripGroup", "da/d15/structmdlpp_1_1VTX_1_1StripGroup.html", null ],
    [ "mdlpp::VTX::Vertex", "d0/d6e/structmdlpp_1_1VTX_1_1Vertex.html", null ],
    [ "mdlpp::VTX::VTX", "d5/dd3/structmdlpp_1_1VTX_1_1VTX.html", null ],
    [ "mdlpp::VVD::BoneWeight", "d8/de6/structmdlpp_1_1VVD_1_1BoneWeight.html", null ],
    [ "mdlpp::VVD::Fixup", "d0/d4d/structmdlpp_1_1VVD_1_1Fixup.html", null ],
    [ "mdlpp::VVD::Vertex", "dc/d30/structmdlpp_1_1VVD_1_1Vertex.html", null ],
    [ "mdlpp::VVD::VVD", "d0/de2/structmdlpp_1_1VVD_1_1VVD.html", null ],
    [ "sourcepp::math::FloatCompressed16", "d4/db7/classsourcepp_1_1math_1_1FloatCompressed16.html", null ],
    [ "sourcepp::math::Matrix< M, N, P >", "d4/d4b/classsourcepp_1_1math_1_1Matrix.html", null ],
    [ "sourcepp::math::QuatCompressed48", "d7/d84/structsourcepp_1_1math_1_1QuatCompressed48.html", null ],
    [ "sourcepp::math::QuatCompressed64", "d4/daf/structsourcepp_1_1math_1_1QuatCompressed64.html", null ],
    [ "sourcepp::math::Vec< S, P >", "d6/d21/structsourcepp_1_1math_1_1Vec.html", null ],
    [ "std::exception", null, [
      [ "std::runtime_error", null, [
        [ "sourcepp::parser::text::syntax_error", "d7/d77/classsourcepp_1_1parser_1_1text_1_1syntax__error.html", null ]
      ] ]
    ] ],
    [ "steampp::Steam", "d9/d81/classsteampp_1_1Steam.html", null ],
    [ "toolpp::CmdSeq", "d5/d62/classtoolpp_1_1CmdSeq.html", null ],
    [ "toolpp::CmdSeq::Command", "d3/df6/structtoolpp_1_1CmdSeq_1_1Command.html", null ],
    [ "toolpp::CmdSeq::Sequence", "da/d0f/structtoolpp_1_1CmdSeq_1_1Sequence.html", null ],
    [ "toolpp::FGD", "d2/d4c/classtoolpp_1_1FGD.html", null ],
    [ "toolpp::FGD::AutoVisGroup", "d0/dcf/structtoolpp_1_1FGD_1_1AutoVisGroup.html", null ],
    [ "toolpp::FGD::Entity", "d8/dc3/structtoolpp_1_1FGD_1_1Entity.html", null ],
    [ "toolpp::FGD::Entity::ClassProperty", "df/dd8/structtoolpp_1_1FGD_1_1Entity_1_1ClassProperty.html", null ],
    [ "toolpp::FGD::Entity::Field", "d2/d9f/structtoolpp_1_1FGD_1_1Entity_1_1Field.html", null ],
    [ "toolpp::FGD::Entity::FieldChoices", "d9/d29/structtoolpp_1_1FGD_1_1Entity_1_1FieldChoices.html", null ],
    [ "toolpp::FGD::Entity::FieldChoices::Choice", "dd/d3e/structtoolpp_1_1FGD_1_1Entity_1_1FieldChoices_1_1Choice.html", null ],
    [ "toolpp::FGD::Entity::FieldFlags", "d0/d54/structtoolpp_1_1FGD_1_1Entity_1_1FieldFlags.html", null ],
    [ "toolpp::FGD::Entity::FieldFlags::Flag", "de/d58/structtoolpp_1_1FGD_1_1Entity_1_1FieldFlags_1_1Flag.html", null ],
    [ "toolpp::FGD::Entity::IO", "de/dc0/structtoolpp_1_1FGD_1_1Entity_1_1IO.html", null ],
    [ "toolpp::FGDWriter", "d5/d25/classtoolpp_1_1FGDWriter.html", null ],
    [ "toolpp::FGDWriter::AutoVisGroupWriter", "d3/d68/classtoolpp_1_1FGDWriter_1_1AutoVisGroupWriter.html", null ],
    [ "toolpp::FGDWriter::EntityWriter", "d4/da2/classtoolpp_1_1FGDWriter_1_1EntityWriter.html", null ],
    [ "toolpp::FGDWriter::EntityWriter::KeyValueChoicesWriter", "db/d88/classtoolpp_1_1FGDWriter_1_1EntityWriter_1_1KeyValueChoicesWriter.html", null ],
    [ "toolpp::FGDWriter::EntityWriter::KeyValueFlagsWriter", "d5/d18/classtoolpp_1_1FGDWriter_1_1EntityWriter_1_1KeyValueFlagsWriter.html", null ],
    [ "uint24_t", "d9/d80/structuint24__t.html", null ],
    [ "vpkpp::BakeOptions", "d0/dff/structvpkpp_1_1BakeOptions.html", null ],
    [ "vpkpp::Entry", "d9/d6b/classvpkpp_1_1Entry.html", null ],
    [ "vpkpp::EntryOptions", "d6/d5b/structvpkpp_1_1EntryOptions.html", null ],
    [ "vpkpp::GCF::Block", "d4/d3e/structvpkpp_1_1GCF_1_1Block.html", null ],
    [ "vpkpp::GCF::BlockHeader", "d9/d14/structvpkpp_1_1GCF_1_1BlockHeader.html", null ],
    [ "vpkpp::GCF::ChecksumMapEntry", "d3/def/structvpkpp_1_1GCF_1_1ChecksumMapEntry.html", null ],
    [ "vpkpp::GCF::ChecksumMapHeader", "dc/db5/structvpkpp_1_1GCF_1_1ChecksumMapHeader.html", null ],
    [ "vpkpp::GCF::DataBlockHeader", "db/ddb/structvpkpp_1_1GCF_1_1DataBlockHeader.html", null ],
    [ "vpkpp::GCF::DirectoryEntry", "d1/d62/structvpkpp_1_1GCF_1_1DirectoryEntry.html", null ],
    [ "vpkpp::GCF::DirectoryEntry2", "dd/de9/structvpkpp_1_1GCF_1_1DirectoryEntry2.html", null ],
    [ "vpkpp::GCF::DirectoryHeader", "d0/d21/structvpkpp_1_1GCF_1_1DirectoryHeader.html", null ],
    [ "vpkpp::GCF::DirectoryMapEntry", "d9/dd6/structvpkpp_1_1GCF_1_1DirectoryMapEntry.html", null ],
    [ "vpkpp::GCF::DirectoryMapHeader", "d4/dcd/structvpkpp_1_1GCF_1_1DirectoryMapHeader.html", null ],
    [ "vpkpp::GCF::Header", "d3/d08/structvpkpp_1_1GCF_1_1Header.html", null ],
    [ "vpkpp::GMA::Header", "dc/d1f/structvpkpp_1_1GMA_1_1Header.html", null ],
    [ "vpkpp::PackFile", "d2/dd2/classvpkpp_1_1PackFile.html", [
      [ "vpkpp::EXAMPLE", "d2/d8b/classvpkpp_1_1EXAMPLE.html", null ],
      [ "vpkpp::GMA", "d6/d2c/classvpkpp_1_1GMA.html", null ],
      [ "vpkpp::PAK", "d9/daf/classvpkpp_1_1PAK.html", null ],
      [ "vpkpp::PCK", "d5/db5/classvpkpp_1_1PCK.html", null ],
      [ "vpkpp::PackFileReadOnly", "de/df6/classvpkpp_1_1PackFileReadOnly.html", [
        [ "vpkpp::GCF", "d1/d01/classvpkpp_1_1GCF.html", null ]
      ] ],
      [ "vpkpp::VPK", "d5/d8b/classvpkpp_1_1VPK.html", [
        [ "vpkpp::FPX", "da/d42/classvpkpp_1_1FPX.html", null ]
      ] ],
      [ "vpkpp::VPK_VTMB", "d4/ddb/classvpkpp_1_1VPK__VTMB.html", null ],
      [ "vpkpp::WAD3", "d1/da5/classvpkpp_1_1WAD3.html", null ],
      [ "vpkpp::ZIP", "da/de7/classvpkpp_1_1ZIP.html", [
        [ "vpkpp::BSP", "d2/da8/classvpkpp_1_1BSP.html", null ]
      ] ]
    ] ],
    [ "vpkpp::PCK::Header", "d5/da3/structvpkpp_1_1PCK_1_1Header.html", null ],
    [ "vpkpp::VPK::Footer2", "d5/dde/structvpkpp_1_1VPK_1_1Footer2.html", null ],
    [ "vpkpp::VPK::FreedChunk", "d9/de4/structvpkpp_1_1VPK_1_1FreedChunk.html", null ],
    [ "vpkpp::VPK::Header1", "d2/d67/structvpkpp_1_1VPK_1_1Header1.html", null ],
    [ "vpkpp::VPK::Header2", "d2/d8d/structvpkpp_1_1VPK_1_1Header2.html", null ],
    [ "vpkpp::VPK::MD5Entry", "dd/dc7/structvpkpp_1_1VPK_1_1MD5Entry.html", null ],
    [ "vtfpp::ImagePixel::A8", "d1/d9a/structvtfpp_1_1ImagePixel_1_1A8.html", null ],
    [ "vtfpp::ImagePixel::ABGR8888", "d3/d83/structvtfpp_1_1ImagePixel_1_1ABGR8888.html", null ],
    [ "vtfpp::ImagePixel::ARGB8888", "d6/dd0/structvtfpp_1_1ImagePixel_1_1ARGB8888.html", null ],
    [ "vtfpp::ImagePixel::BGR565", "d9/d48/structvtfpp_1_1ImagePixel_1_1BGR565.html", null ],
    [ "vtfpp::ImagePixel::BGR888", "d8/d63/structvtfpp_1_1ImagePixel_1_1BGR888.html", [
      [ "vtfpp::ImagePixel::BGR888_BLUESCREEN", "d2/dd2/structvtfpp_1_1ImagePixel_1_1BGR888__BLUESCREEN.html", null ]
    ] ],
    [ "vtfpp::ImagePixel::BGRA1010102", "de/d7c/structvtfpp_1_1ImagePixel_1_1BGRA1010102.html", null ],
    [ "vtfpp::ImagePixel::BGRA4444", "d0/d1c/structvtfpp_1_1ImagePixel_1_1BGRA4444.html", null ],
    [ "vtfpp::ImagePixel::BGRA5551", "dd/d5e/structvtfpp_1_1ImagePixel_1_1BGRA5551.html", null ],
    [ "vtfpp::ImagePixel::BGRA8888", "d5/d7f/structvtfpp_1_1ImagePixel_1_1BGRA8888.html", null ],
    [ "vtfpp::ImagePixel::BGRX5551", "d9/d8a/structvtfpp_1_1ImagePixel_1_1BGRX5551.html", null ],
    [ "vtfpp::ImagePixel::BGRX8888", "d0/d15/structvtfpp_1_1ImagePixel_1_1BGRX8888.html", null ],
    [ "vtfpp::ImagePixel::I8", "d2/d77/structvtfpp_1_1ImagePixel_1_1I8.html", null ],
    [ "vtfpp::ImagePixel::IA88", "da/d07/structvtfpp_1_1ImagePixel_1_1IA88.html", null ],
    [ "vtfpp::ImagePixel::P8", "d9/d3a/structvtfpp_1_1ImagePixel_1_1P8.html", null ],
    [ "vtfpp::ImagePixel::R16F", "dc/d23/structvtfpp_1_1ImagePixel_1_1R16F.html", null ],
    [ "vtfpp::ImagePixel::R32F", "de/da1/structvtfpp_1_1ImagePixel_1_1R32F.html", null ],
    [ "vtfpp::ImagePixel::R8", "d8/d14/structvtfpp_1_1ImagePixel_1_1R8.html", null ],
    [ "vtfpp::ImagePixel::RG1616F", "d6/d4c/structvtfpp_1_1ImagePixel_1_1RG1616F.html", null ],
    [ "vtfpp::ImagePixel::RG3232F", "db/d93/structvtfpp_1_1ImagePixel_1_1RG3232F.html", null ],
    [ "vtfpp::ImagePixel::RGB323232F", "d0/d5b/structvtfpp_1_1ImagePixel_1_1RGB323232F.html", null ],
    [ "vtfpp::ImagePixel::RGB565", "d0/d92/structvtfpp_1_1ImagePixel_1_1RGB565.html", null ],
    [ "vtfpp::ImagePixel::RGB888", "d0/d24/structvtfpp_1_1ImagePixel_1_1RGB888.html", [
      [ "vtfpp::ImagePixel::RGB888_BLUESCREEN", "d1/d7e/structvtfpp_1_1ImagePixel_1_1RGB888__BLUESCREEN.html", null ]
    ] ],
    [ "vtfpp::ImagePixel::RGBA1010102", "d4/d5b/structvtfpp_1_1ImagePixel_1_1RGBA1010102.html", null ],
    [ "vtfpp::ImagePixel::RGBA16161616", "d9/d32/structvtfpp_1_1ImagePixel_1_1RGBA16161616.html", null ],
    [ "vtfpp::ImagePixel::RGBA16161616F", "d0/de9/structvtfpp_1_1ImagePixel_1_1RGBA16161616F.html", null ],
    [ "vtfpp::ImagePixel::RGBA32323232F", "d0/d9a/structvtfpp_1_1ImagePixel_1_1RGBA32323232F.html", null ],
    [ "vtfpp::ImagePixel::RGBA8888", "de/d5a/structvtfpp_1_1ImagePixel_1_1RGBA8888.html", null ],
    [ "vtfpp::ImagePixel::RGBX8888", "d0/dc9/structvtfpp_1_1ImagePixel_1_1RGBX8888.html", null ],
    [ "vtfpp::ImagePixel::UV88", "dd/d67/structvtfpp_1_1ImagePixel_1_1UV88.html", null ],
    [ "vtfpp::ImagePixel::UVLX8888", "d3/df9/structvtfpp_1_1ImagePixel_1_1UVLX8888.html", null ],
    [ "vtfpp::ImagePixel::UVWQ8888", "dd/d9f/structvtfpp_1_1ImagePixel_1_1UVWQ8888.html", null ],
    [ "vtfpp::PPL", "df/d32/classvtfpp_1_1PPL.html", null ],
    [ "vtfpp::PPL::Image", "d1/dc9/structvtfpp_1_1PPL_1_1Image.html", null ],
    [ "vtfpp::Resource", "d3/d80/structvtfpp_1_1Resource.html", null ],
    [ "vtfpp::VTF", "d8/df2/classvtfpp_1_1VTF.html", null ],
    [ "vtfpp::VTF::CreationOptions", "d3/d2b/structvtfpp_1_1VTF_1_1CreationOptions.html", null ]
];