macro(sourcepp_bench_setup)
    if(SOURCEPP_BUILD_BENCHMARKS)
        set(SOURCEPP_BENCH_NAME "${PROJECT_NAME}_bench")
        set(BENCHMARK_ENABLE_TESTING OFF CACHE INTERNAL "" FORCE)
        add_sourcepp_remote_library(benchmark https://github.com/google/benchmark main ALLOW_NOT_PINNED)
        add_library(${SOURCEPP_BENCH_NAME} STATIC "${CMAKE_CURRENT_SOURCE_DIR}/bench/_bench.cpp")
        target_link_libraries(${SOURCEPP_BENCH_NAME} PUBLIC benchmark::benchmark)
        target_compile_definitions(${SOURCEPP_BENCH_NAME} PUBLIC ASSET_ROOT="${CMAKE_CURRENT_SOURCE_DIR}/test/res/")
    endif()
endmacro()
