include_guard(GLOBAL)

include(FetchContent)

function(add_sourcepp_remote_library NAME REPOSITORY TAG)
    cmake_parse_arguments(PARSE_ARGV 3 OPTIONS "ALLOW_NOT_PINNED;DO_NOT_USE_CMAKELISTS;EXCLUDE_FROM_ALL;OVERRIDE_FIND_PACKAGE" "" "")
    if(NOT OPTIONS_ALLOW_NOT_PINNED)
        string(LENGTH "${TAG}" TAG_SIZE)
        if(NOT TAG_SIZE EQUAL 40)
            message(FATAL_ERROR "For the sake of making SourcePP builds reproducible, dependencies must be pinned to specific commits. ${NAME} is not.")
        endif()
    endif()
    if(NOT TARGET NAME)
        message(STATUS "Fetching ${NAME} ${REPOSITORY} ${TAG}")
        string(REPLACE ":" "_" NAME_CLEAN "${NAME}")
        set(FETCHCONTENT_DECLARE_ARGUMENTS "${NAME_CLEAN}" "GIT_REPOSITORY" "${REPOSITORY}.git" "GIT_TAG" "${TAG}")
        if(OPTIONS_DO_NOT_USE_CMAKELISTS)
            list(APPEND FETCHCONTENT_DECLARE_ARGUMENTS "SOURCE_SUBDIR" "THIS_DIRECTORY_DOES_NOT_EXIST")
        endif()
        if(OPTIONS_EXCLUDE_FROM_ALL)
            list(APPEND FETCHCONTENT_DECLARE_ARGUMENTS "EXCLUDE_FROM_ALL")
        endif()
        if(OPTIONS_OVERRIDE_FIND_PACKAGE)
            list(APPEND FETCHCONTENT_DECLARE_ARGUMENTS "OVERRIDE_FIND_PACKAGE")
        endif()
        FetchContent_Declare(${FETCHCONTENT_DECLARE_ARGUMENTS})
        FetchContent_MakeAvailable(${NAME_CLEAN})
    endif()
    return(PROPAGATE "${NAME_CLEAN}_POPULATED" "${NAME_CLEAN}_SOURCE_DIR" "${NAME_CLEAN}_BINARY_DIR")
endfunction()
