include_guard(GLOBAL)

function(print_options)
    cmake_parse_arguments(PARSE_ARGV 0 IN "" "" "OPTIONS")
    foreach (OPT ${IN_OPTIONS})
        if(OPT MATCHES "\n")
            message(STATUS "")
        elseif(SOURCEPP_${OPT})
            message(STATUS "[X] SOURCEPP_${OPT}")
        else()
            message(STATUS "[ ] SOURCEPP_${OPT}")
        endif()
    endforeach()
endfunction()
