function(print_options)
    cmake_parse_arguments(PARSE_ARGV 0 IN "" "" "OPTIONS")
    foreach (OPT ${IN_OPTIONS})
        if(SOURCEPP_${OPT})
            message(STATUS "[X] SOURCEPP_${OPT}")
        else()
            message(STATUS "[ ] SOURCEPP_${OPT}")
        endif()
    endforeach()
endfunction()
