name: Deploy Docs

on:
  push:
    branches: [main]
  workflow_dispatch:
  # nothing here

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Create & Deploy Docs
        uses: DenverCoder1/doxygen-github-pages-action@v2.0.0
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          branch: docs
